name: app
description: A cross-platform desktop app built with Dart and Electron.
publish_to: none

environment:
  sdk: ">=2.0.0 <=3.0.0"

dependencies:
  angular: ^5.3.0
  angular_forms: ^2.1.1
  http: ^0.12.0
  intl: ^0.15.7
  js: ^0.6.0
  logging: ^0.11.3
  meta: ^1.2.0
  node_interop: ^1.1.0
  uuid: ^2.2.0
  rxdart: ^0.24.0

dev_dependencies:
  build_runner: ^1.9.0
  build_web_compilers: ^2.0.0
